controller:
  ingressClass: nginx-external-new
  
  replicaCount: 1


  service:
    enabled: true

    annotations:
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"

  nodeSelectors: {}

  tolerations: []

# Istio changes to not add the istio sidecar to the prometheus operator's addmission webhook patch
# https://github.com/prometheus-community/helm-charts/issues/479#issuecomment-752709725
  admissionWebhooks:
    annotations:
      sidecar.istio.io/inject: "false"
